modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "cydun"
version = "0.5"
displayName = "Cyclic Dungeons"
authors = "Lying"
description = '''
Smarter dungeons for the avid adventurer
'''
#logoFile = "icon.png"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.cydun]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cydun]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cydun]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cydun.mixins.json"
